FROM quay.io/centos-bootc/centos-bootc-dev:stream9

COPY ./etc/. /etc
COPY ./usr/. /usr

# custom auth file
COPY ./auth.json /root/auth.json

ARG sshpubkey

RUN dnf -y install lldb firewalld vim && \
    firewall-offline-cmd --add-port 1025-65535/tcp && \
    systemctl enable lldb-server.service && \

    # add test user
    if test -z "$sshpubkey"; then echo "must provide sshpubkey"; exit 1; fi; \
    useradd -G wheel test && \
    mkdir -m 0700 -p /home/test/.ssh && \
    echo $sshpubkey > /home/test/.ssh/authorized_keys && \
    chmod 0600 /home/test/.ssh/authorized_keys && \
    chown -R test: /home/test && \

    # link bound image
    mkdir -p /usr/lib/bootc-experimental/bound-images.d && \
    ln -s /usr/share/containers/systemd/alpine.container /usr/lib/bootc-experimental/bound-images.d/alpine.container && \
    ln -s /usr/share/containers/systemd/ubi-minimal.image /usr/lib/bootc-experimental/bound-images.d/ubi-minimal.image
